name: Garde mon Repl éveillé

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping_repl:
    runs-on: ubuntu-latest
    steps:
      - name: Envoyer un ping à mon Repl
        run: |
          curl -m 10 -I https://e97b155e-defc-48c7-b67c-08562fc3e0e8-00-39voigsjgjd4e.worf.replit.dev/ || true
